routes/web.php
<?php
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\WelcomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::get('categories/export/', [CategoryController::class, 'export'])->name('categories.export');

Route::get('categories/pdf/', [CategoryController::class, 'downloadPdf'])->name('categories.pdf');

Route::get('/trashed-categories', [CategoryController::class, 'trash'])->name('categories.trashed');

Route::get('/trashed-categories/{category}/restore', [CategoryController::class, 'restore'])->name('categories.restore');

Route::delete('/trashed-categories/{category}/delete', [CategoryController::class, 'delete'])->name('categories.delete');

Route::resource('categories', CategoryController::class);

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use HasFactory, SoftDeletes;
    
    // protected $fillable = [
    //     'title',
    //     'description'
    // ];

    protected $guarded = [];

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Exports\CategoryExport;
use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Image;
use Excel;
use PDF;

class CategoryController extends Controller
{
    public function index()
    {
        $categories = Category::latest()->get();
        return view('backend.categories.index', [
            'categories' => $categories
        ]);
    }

    public function create()
    {
        return view('backend.categories.create');
    }

    public function store(CategoryRequest $request)
    {
        try {           
            Category::create([
                'title' => $request->title,
                'description' => $request->description,
                'image' => $this->uploadImage(request()->file('image'))
            ]);

            return redirect()->route('categories.index')->withMessage('Successfully Created!');
        } catch (QueryException $e) {
            return redirect()->back()->withInput()->withErrors($e->getMessage());
        }
    }

    public function show(Category $category)
    {
        return view('backend.categories.show', [
            'category' => $category
        ]);
    }

    public function edit(Category $category)
    {
        return view('backend.categories.edit', [
            'category' => $category
        ]);
    }

    public function update(CategoryRequest $request, Category $category)
    {
        try {
            $requestData = [
                'title' => $request->title,
                'description' => $request->description,
            ];

            if($request->hasFile('image')){
                $requestData['image'] = $this->uploadImage(request()->file('image'));
            }

            $category->update($requestData);

            return redirect()->route('categories.index')->withMessage('Successfully Updated!');
        } catch (QueryException $e) {
            return redirect()->back()->withInput()->withErrors($e->getMessage());
        }
    }

    public function destroy(Category $category)
    {
        try {
            $category->delete();
            return redirect()->route('categories.index')->withMessage('Successfully Deleted!');
        } catch (QueryException $e) {
            return redirect()->back()->withErrors($e->getMessage());
        }
    }

    // Softdelete
    public function trash()
    {
        $categories = Category::onlyTrashed()->get();

        return view('backend.categories.trashed', [
            'categories' => $categories
        ]);        
    }

    public function restore($id)
    {
        $category = Category::onlyTrashed()->findOrFail($id);
        $category->restore();
        return redirect()->route('categories.trashed')->withMessage('Successfully Restored!');
    }

    public function delete($id)
    {
        $category = Category::onlyTrashed()->findOrFail($id);
        $category->forceDelete();
        return redirect()->route('categories.trashed')->withMessage('Successfully Deleted Permanently!');
    }

    public function uploadImage($file)
    {        
        $fileName = time().'.'.$file->getClientOriginalExtension();
        Image::make($file)
                ->resize(200, 200)
                ->save(storage_path().'/app/public/images/'.$fileName);
        return $fileName;
    }

    public function export() 
    {
        return Excel::download(new CategoryExport, 'categories.xlsx');
    }

    public function downloadPdf()
    {
        $categories = Category::all();
        $pdf = PDF::loadView('backend.categories.pdf', compact('categories'));
        return $pdf->download('categories.pdf');
    }

}

resources/views/backend/categories/create.blade.php
<x-backend.layouts.master>
    <x-slot name="pageTitle">
        Add Form
    </x-slot>

    <x-slot name='breadCrumb'>
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader"> Categories </x-slot>

            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
            <li class="breadcrumb-item active">Add New</li>

        </x-backend.layouts.elements.breadcrumb>
    </x-slot>


    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Create Category <a class="btn btn-sm btn-info" href="{{ route('categories.index') }}">List</a>
        </div>
        <div class="card-body">

           <x-backend.layouts.elements.errors :errors="$errors"/>

            <form action="{{ route('categories.store') }}" enctype="multipart/form-data" method="post">
                @csrf
                <x-backend.form.input name="title"/>                
                
                <x-backend.form.textarea name="description" />

                <x-backend.form.input name="image" type="file"/>

                <x-backend.form.button>Save</x-backend.form.button>
            </form>
        </div>
    </div>


</x-backend.layouts.master>

resources/views/backend/categories/edit.blade.php
<x-backend.layouts.master>
    <x-slot name="pageTitle">
        Edit Form
    </x-slot>

    <x-slot name='breadCrumb'>
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader"> Categories </x-slot>

            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
            <li class="breadcrumb-item active">Edit</li>

        </x-backend.layouts.elements.breadcrumb>
    </x-slot>


    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Edit Category <a class="btn btn-sm btn-info" href="{{ route('categories.index') }}">List</a>
        </div>
        <div class="card-body">

            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif

            <form action="{{ route('categories.update', ['category' => $category->id]) }}" method="post" enctype="multipart/form-data">
                @csrf
                @method('patch')

                <x-backend.form.input name="title" :value="$category->title" />               
                <x-backend.form.textarea name="description">
                {{ $category->description }}
                </x-backend.form.textarea>

                <x-backend.form.input name="image" type="file" :value="$category->image"/>                

                <x-backend.form.button>Update</x-backend.form.button>

            </form>
        </div>
    </div>


</x-backend.layouts.master>

resources/views/backend/categories/index.blade.php
<x-backend.layouts.master>
    <x-slot name="pageTitle">
        Categories
    </x-slot>

    <x-slot name='breadCrumb'>
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader"> Categories </x-slot>

            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
            <li class="breadcrumb-item active">Categories</li>

        </x-backend.layouts.elements.breadcrumb>
    </x-slot>

    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Categories 
            <a class="btn btn-sm btn-primary" href="{{ route('categories.export') }}">Excel Export</a>
            <a class="btn btn-sm btn-primary" href="{{ route('categories.pdf') }}">PDF Download</a>
            <a class="btn btn-sm btn-danger" href="{{ route('categories.trashed') }}">Trashed List</a>
             <a class="btn btn-sm btn-info" href="{{ route('categories.create') }}">Add New</a>
        </div>
        <div class="card-body">

           <x-backend.layouts.elements.message :message="session('message')" />

            <table id="datatablesSimple">
                <thead>
                    <tr>
                        <th>Sl#</th>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @php $sl=0 @endphp
                    @foreach ($categories as $category)
                    <tr>
                        <td>{{ ++$sl }}</td>
                        <td>{{ $category->title }}</td>
                        <td>{{ $category->description }}</td>
                        <td>
                            <a class="btn btn-info btn-sm" href="{{ route('categories.show', ['category' => $category->id]) }}" >Show</a>

                            <a class="btn btn-warning btn-sm" href="{{ route('categories.edit', ['category' => $category->id]) }}" >Edit</a>

                            <form style="display:inline" action="{{ route('categories.destroy', ['category' => $category->id]) }}" method="post">
                                @csrf
                                @method('delete')
                                
                                <button onclick="return confirm('Are you sure want to delete ?')" class="btn btn-sm btn-danger" type="submit">Delete</button>
                            </form>

                            <!-- <a href="{{ route('categories.destroy', ['category' => $category->id]) }}" >Delete</a> -->


                        </td>
                    </tr>
                    @endforeach

                </tbody>
            </table>
        </div>
    </div>

</x-backend.layouts.master>

resources/views/backend/categories/pdf.blade.php
<table id="datatablesSimple" border="1">
    <thead>
        <tr>
            <th>Sl#</th>
            <th>Title</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
    @php $sl=0 @endphp
        @foreach ($categories as $category)
        <tr>
            <td>{{ ++$sl }}</td>
            <td>{{ $category->title }}</td>
            <td>{{ $category->description }}</td>
            
        </tr>
        @endforeach

    </tbody>
</table>

resources/views/backend/categories/show.blade.php
<x-backend.layouts.master>
    <x-slot name="pageTitle">
        Details
    </x-slot>

    <x-slot name='breadCrumb'>
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader"> Categories </x-slot>

            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
            <li class="breadcrumb-item active">Add New</li>

        </x-backend.layouts.elements.breadcrumb>
    </x-slot>

    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
           Category Details <a class="btn btn-sm btn-info" href="{{ route('categories.index') }}">List</a>
        </div>
        <div class="card-body">
            <h3>Title: {{ $category->title }}</h3>
            <p>Description: {{ $category->description }}</p>
            <img src="{{ asset('storage/images/'.$category->image) }}" />
        </div>
    </div>

</x-backend.layouts.master>

resources/views/backend/categories/trashed.blade.php
<x-backend.layouts.master>
    <x-slot name="pageTitle">
        Categories
    </x-slot>

    <x-slot name='breadCrumb'>
        <x-backend.layouts.elements.breadcrumb>
            <x-slot name="pageHeader"> Categories </x-slot>

            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
            <li class="breadcrumb-item active">Categories</li>

        </x-backend.layouts.elements.breadcrumb>
    </x-slot>

    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Categories <a class="btn btn-sm btn-info" href="{{ route('categories.index') }}">List</a>
        </div>
        <div class="card-body">

            @if (session('message'))
            <div class="alert alert-success">
                <span class="close" data-dismiss="alert">&times;</span>
                <strong>{{ session('message') }}.</strong>
            </div>
            @endif

            <table id="datatablesSimple">
                <thead>
                    <tr>
                        <th>Sl#</th>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @php $sl=0 @endphp
                    @foreach ($categories as $category)
                    <tr>
                        <td>{{ ++$sl }}</td>
                        <td>{{ $category->title }}</td>
                        <td>{{ $category->description }}</td>
                        <td>
                        
                            <a class="btn btn-warning btn-sm" href="{{ route('categories.restore', ['category' => $category->id]) }}" >Restore</a>

                            <form style="display:inline" action="{{ route('categories.delete', ['category' => $category->id]) }}" method="post">
                                @csrf
                                @method('delete')
                                
                                <button onclick="return confirm('Are you sure want to delete permanently?')" class="btn btn-sm btn-danger" type="submit">Permanent Delete</button>
                            </form>

                        </td>
                    </tr>
                    @endforeach

                </tbody>
            </table>
        </div>
    </div>

</x-backend.layouts.master>